baseURL = "https://watarineko.github.io/blog"
languageCode = "en-us"
title = "狂っちまった悲しみに"
theme = "hugo-theme-anubis"
paginate = 10
publishDir = "docs"

disqusShortname = ""
googleAnalytics = ""

[author]
  name = "Shion Machida"

[params]
   author = "Shion Machida"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

[taxonomies]
category = "categories"
tag = "tags"
series = "series"